#language: groovy
#
#script:
#  gradle cucumber
#  gradle assemble
#  gradle check
#
#after_success:
#    - bash <(curl -s https://codecov.io/bash)


#language: java
#jdk:
#  - oraclejdk8


language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew cucumber
